export const BLOG_OBJECTS = [
  {
    id: 'notes-source',
    zoneId: 'center-desk',
    title: '近日手札',
    subtitle: '最新文章、设计过程、技术记录',
    description: '临时记录、阶段复盘和最近写下的技术碎片都先收在这里。',
    assetKey: 'notes.source',
    panelType: 'cards',
    placement: {
      left: '51.968%',
      top: '60.037%',
      width: '14.986%',
      rotate: '-30deg',
      opacity: 1,
    },
    tooltip: '近日手札',
    entries: ['最新文章', '设计过程', '技术记录'],
    enabled: true,
  },
  {
    id: 'mapbook-main',
    zoneId: 'travel-zone',
    title: '旅行地图册',
    subtitle: '路线、城市和散步计划',
    description: '把旅行路线、城市节点和地图界面做成可以反复翻看的路线册。',
    assetKey: 'mapbook.source',
    panelType: 'book',
    placement: {
      left: '52.4%',
      top: '85.2%',
      width: '57.6%',
      rotate: '-4deg',
      opacity: 1,
    },
    tooltip: '旅行地图册',
    entries: ['3D 旅游路线地图', '杭州巡游计划', '旅行节点手札'],
    enabled: false,
  },
  {
    id: 'index-main',
    zoneId: 'left-shelf',
    title: '节点索引册',
    subtitle: 'Obsidian 图谱、知识整理、旅行节点抽取',
    description: '把散落的笔记、路线、设定和技术记录整理成可追踪的节点系统。',
    assetKey: 'index.source',
    panelType: 'notebook',
    placement: {
      left: '50%',
      top: '50%',
      width: '18%',
      rotate: '0deg',
      opacity: 1,
    },
    tooltip: '节点索引册',
    entries: ['Obsidian 图谱', '知识整理', '旅行节点抽取实验'],
    enabled: false,
  },
  {
    id: 'scroll-main',
    zoneId: 'scroll-zone',
    title: '旧地图卷轴',
    subtitle: '现实地形幻想转译、小说世界观地图志',
    description: '把现实地形、城市经验和故事设定折进一张更像传说的地图里。',
    assetKey: 'scroll.source',
    panelType: 'scroll',
    placement: {
      left: '50%',
      top: '55%',
      width: '24%',
      rotate: '0deg',
      opacity: 1,
    },
    tooltip: '旧地图卷轴',
    entries: ['现实地形的幻想转译', '小说世界观地图志', '旧设定归档'],
    enabled: false,
  },
  {
    id: 'mech-main',
    zoneId: 'right-shelf',
    title: '机关技术书',
    subtitle: 'Three.js、前端实验、交互式地图界面',
    description: '收藏网页视觉实验、3D 组件、地图交互和一些会动的小机关。',
    assetKey: 'mech.source',
    panelType: 'mechanism',
    placement: {
      left: '50%',
      top: '50%',
      width: '18%',
      rotate: '0deg',
      opacity: 1,
    },
    tooltip: '机关技术书',
    entries: ['Three.js 视觉实验', '前端实验', '交互式地图界面'],
    enabled: false,
  },
];
